"""Public contract for the data science agent."""

from dsa.benchmark import (
    BenchmarkCell,
    BenchmarkCellReceipt,
    BenchmarkDatasetBinding,
    BenchmarkExecution,
    BenchmarkModel,
    BenchmarkPack,
    BenchmarkPlan,
    BenchmarkRuntime,
    BenchmarkStudy,
    PreparedBenchmark,
    benchmark_plan,
    expand_benchmark_study,
    prepare_benchmark,
    read_benchmark_cell_receipt,
    run_prepared_benchmark,
)
from dsa.benchmark_report import (
    BenchmarkReport,
    RetainedBenchmarkReport,
    build_benchmark_report,
    publish_benchmark_report,
)
from dsa.contract import ModelConfiguration, RunPolicy, RunRequest
from dsa.docker import (
    DockerExecutorConfiguration,
    DockerPythonExecutor,
    default_docker_configuration,
)
from dsa.environment import (
    PythonExecutionError,
    PythonExecutionRequest,
    PythonExecutionResult,
    PythonExecutor,
)
from dsa.evaluation import (
    MlflowEvaluationError,
    MlflowEvaluationPrediction,
    MlflowEvaluationResult,
    run_mlflow_evaluation,
)
from dsa.pack import (
    EvaluationPackCase,
    EvaluationPackError,
    EvaluationPackManifest,
    HuggingFacePackReference,
    LoadedEvaluationPack,
    load_huggingface_evaluation_pack,
)
from dsa.record import (
    ArtifactRecord,
    DatabaseRecord,
    Failure,
    RetainedTerminalRecord,
    RunFailure,
    RunSuccess,
    TerminalRecord,
    write_terminal_record,
)
from dsa.reporting import MlflowReporting
from dsa.runner import RunCompletion, run_analysis

__all__ = [
    "ArtifactRecord",
    "BenchmarkCell",
    "BenchmarkCellReceipt",
    "BenchmarkDatasetBinding",
    "BenchmarkExecution",
    "BenchmarkModel",
    "BenchmarkPack",
    "BenchmarkPlan",
    "BenchmarkReport",
    "BenchmarkRuntime",
    "BenchmarkStudy",
    "DatabaseRecord",
    "DockerExecutorConfiguration",
    "DockerPythonExecutor",
    "EvaluationPackCase",
    "EvaluationPackError",
    "EvaluationPackManifest",
    "Failure",
    "HuggingFacePackReference",
    "LoadedEvaluationPack",
    "MlflowEvaluationError",
    "MlflowEvaluationPrediction",
    "MlflowEvaluationResult",
    "MlflowReporting",
    "ModelConfiguration",
    "PreparedBenchmark",
    "PythonExecutionError",
    "PythonExecutionRequest",
    "PythonExecutionResult",
    "PythonExecutor",
    "RetainedBenchmarkReport",
    "RetainedTerminalRecord",
    "RunCompletion",
    "RunFailure",
    "RunPolicy",
    "RunRequest",
    "RunSuccess",
    "TerminalRecord",
    "benchmark_plan",
    "build_benchmark_report",
    "default_docker_configuration",
    "expand_benchmark_study",
    "load_huggingface_evaluation_pack",
    "prepare_benchmark",
    "publish_benchmark_report",
    "read_benchmark_cell_receipt",
    "run_analysis",
    "run_mlflow_evaluation",
    "run_prepared_benchmark",
    "write_terminal_record",
]
